json.extract! @listing,
    :id,
    :owner_id,
    :city,
    :zip_code,
    :state,
    :country,
    :lat,
    :long,
    :tags,
    :property_type,
    :max_guests,
    :night_price,
    :cleaning_fee,
    :description,
    :num_bedrooms,
    :num_beds,
    :num_baths,
    :amenities,
    :tag_line,
    :max_guests
json.imgUrls @listing.photos.map { |photo| photo.url }
json.extract! @owner,
    :first_name,
    :bio,
    :created_at
json.ownerPic @owner.photo.url